name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/compose-cli-action@v0.8.0
        with:
          compose-file: docker-compose.yaml

      - name: Build and tag Docker images
        run: docker-compose build

      - name: Push Docker images to registry
        run: docker-compose push
